version '3.8'

services:
  db:
  image: postgis/postgis:15-3.3
  container_name: geo-db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: group_geo
  ports:
    - "5432:5432"
  volumes:
    - db-data:/var/lib/postgresql/data

api:
  build:
    context: ./GroupGeoCheckin.API
  ports:
    - "5000:80"
  depends_on:
    - db
  environment:
    - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=password;Database=group_geo
    - ASPNETCORE_ENVIRONMENT=Development

  volumes:
    -db-data:/var/lib/postgresql/data